version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
      - 5050:5050
    volumes:
      - ./conf/vhosts:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./www/:/var/www/
  tomat:
    container_name: tomcat
    restart: always
    image: tomcat:8.0
    ports:
      - 8080:8080
      - 8009:8009
    volumes:
      - ./webapps/countuser-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/countuser-1.0-SNAPSHOT.war
      - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./logs:/usr/local/tomcat/logs
      

